backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Titel", name: "titel", widget: "string" }
          - { label: "Untertitel", name: "untertitel", widget: "string" }
          - label: "Bücher"
            name: "buecher"
            widget: "list"
            fields:
              - { label: "Buchtitel", name: "buchtitel", widget: "string" }
              - { label: "Autor", name: "autor", widget: "string" }
              - { label: "Beschreibung", name: "beschreibung", widget: "text" }
              - { label: "Cover", name: "cover", widget: "image" }
