backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Titel", name: "titel", widget: "string" }
          - { label: "Text", name: "text", widget: "text" }
          - { label: "Bild", name: "bild", widget: "image" }
